### ISSUE TITLE
Disk usage 

### ISSUE THREAD

**Issue by glynhudson** [shellhub-io/shellhub#1929]
I'm running Shellhub V0.9.2 via docker with 17 clients connected. I've noticed even when not in use the disk usage on the Shellhub server continually increases. After running for a few months disk usage is now 87% of 25GB. Is this normal? Presumably the increasing disk usage is due to logging? Can I reduce this? 

![Screenshot from 2022-05-24 11-28-03](https://user-images.githubusercontent.com/758844/170011228-59820686-d18e-4c50-8abe-22a1ac11404c.png)

**Comment by gustavosbarreto** [comment]
You can clear container logs and set a maximum size on docker to make sure that this doesn't happen again

**Comment by glynhudson** [comment]
Agh I never got round to doing this, just checked my shellhub instance today and the logs had reached 100% disk space (25GB) which resulted in the mongo db getting corrupted. Luckily I had a backup I was able to restore from. 

I now need to implement a maximum size for the docker logs. Do you have a recommended way to do this without deviating too much from a standard shellhub install?

**Comment by otavio** [comment]
There is the docker-compose override file, intended for local customizations. Hope it helps.

**Comment by glynhudson** [comment]
Ok, thanks. Hopefully this `docker-compose.override.yml ` will do the trick 

```
version: '3.7'
services:
  mongo:
    volumes:
      - /usr/local/mongo/data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
````
