### ISSUE TITLE
docker-compose exec cli gives: /dev/ptmx: operation not permitted

### ISSUE THREAD

**Issue by peterge1998** [shellhub-io/shellhub#2343]
### Description

I just discovered the project and tried to set it up because it looks very promising!

However, I stumbled about this error when I run  `./bin/add-user`:
```
root@shellhub:~/shellhub# make start
Starting ShellHub in production mode...

WARNING: The SHELLHUB_TELEMETRY variable is not set. Defaulting to a blank string.
WARNING: The SHELLHUB_TELEMETRY_SCHEDULE variable is not set. Defaulting to a blank string.
watchtower is up-to-date
shellhub_mongo_1 is up-to-date
shellhub_ssh_1 is up-to-date
shellhub_redis_1 is up-to-date
shellhub_api_1 is up-to-date
shellhub_ui_1 is up-to-date
shellhub_cli_1 is up-to-date
shellhub_gateway_1 is up-to-date

root@shellhub:~/shellhub# docker ps 
CONTAINER ID   IMAGE                        COMMAND                  CREATED          STATUS                         PORTS                                   NAMES
8fb496fdd2a3   containrrr/watchtower        "/watchtower"            12 minutes ago   Up 12 minutes                  8080/tcp                                watchtower
9e3b930048d9   shellhubio/gateway:v0.10.9   "/entrypoint.sh /usr…"   18 minutes ago   Up 18 minutes                  0.0.0.0:80->80/tcp, :::80->80/tcp       shellhub_gateway_1
725c47d7bf59   shellhubio/cli:v0.10.9       "/bin/sleep infinity"    18 minutes ago   Up 18 minutes                                                          shellhub_cli_1
150e623e072a   shellhubio/ui:v0.10.9        "/docker-entrypoint.…"   18 minutes ago   Up 18 minutes                  80/tcp                                  shellhub_ui_1
55529d8df02c   shellhubio/api:v0.10.9       "/bin/sh -c '/api se…"   18 minutes ago   Restarting (1) 5 seconds ago                                           shellhub_api_1
55a79722861d   redis                        "docker-entrypoint.s…"   18 minutes ago   Up 18 minutes                  6379/tcp                                shellhub_redis_1
1b219805695c   shellhubio/ssh:v0.10.9       "/bin/sh -c /ssh"        18 minutes ago   Up 15 minutes                  0.0.0.0:22->2222/tcp, :::22->2222/tcp   shellhub_ssh_1
43fd2249c87c   mongo:4.4.8                  "docker-entrypoint.s…"   18 minutes ago   Up 18 minutes (unhealthy)      27017/tcp                               shellhub_mongo_1

root@shellhub:~/shellhub# ./bin/add-user peterge password mail@peterge.de
OCI runtime exec failed: exec failed: unable to start container process: open /dev/ptmx: operation not permitted: unknown

root@shellhub:~/shellhub# docker-compose logs cli
Attaching to shellhub_cli_1
```
cli is showing nothing in its logs at all...

I cant exec cli at all:
```
root@shellhub:~/shellhub# docker-compose exec cli /bin/bash
OCI runtime exec failed: exec failed: unable to start container process: open /dev/ptmx: operation not permitted: unknown
```

### Edition

Community

### Version

v0.10.9

**Comment by gustavosbarreto** [comment]
What operating system are you using?

**Comment by peterge1998** [comment]
debian 11

**Comment by peterge1998** [comment]
```
root@shellhub:~/shellhub# docker-compose exec cli /bin/sh
OCI runtime exec failed: exec failed: unable to start container process: open /dev/ptmx: operation not permitted: unknown
```
I use docker.
```
root@shellhub:~/shellhub# cat docker-compose.override.yml 
version: '3.7'
services:
  mongo:
    volumes:
      - /usr/local/mongo/data:/data/db
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_SCHEDULE=0 15 12 * * *
      - WATCHTOWER_CLEANUP=true
      - TZ=Europe/Berlin
      - WATCHTOWER_NOTIFICATIONS=email

root@shellhub:~/shellhub# runc --version
runc version 1.1.4
commit: v1.1.4-0-g5fd4c4d
spec: 1.0.2-dev
go: go1.18.9
libseccomp: 2.5.1
root@shellhub:~/shellhub# docker --version
Docker version 20.10.22, build 3a2c30b
```
